### ISSUE TITLE
[Feature Request] Don't account for EditorOnly tagged GameObjects when counting texture size

### ISSUE THREAD

**Issue by TayouVR** [Thryrallo/VRCAvatarTools#3]
Editor Only tags are not built and exported into assetBundles, therefore they shouldn't be accounted for.
I believe the linq expression here: https://github.com/Thryrallo/VRCAvatarTools/blob/3eeb854040497c4ae5b331f30efac625a2183249/AvatarEvaluator.cs#L264
would need to be adjusted to select only gameObjects with a tag != EditorOnly.

If I can figure this out myself I'll do a PR and reference this issue, otherwise I'd love if someone else could do it.

**Comment by Thryrallo** [comment]
done
